//! Trait mocking for Midje-style `provided!` expectations.
//!
//! The [`mockable!`](crate::mockable) macro defines a trait alongside a mock
//! struct whose fields are `RefCell<Option<Return>>` slots — one per trait
//! method. [`provided!`](crate::provided) is sugar for setting those slots.
//!
//! Scope of the stub:
//! - `&self` methods only (interior mutability via `RefCell`).
//! - Return type must be `Clone` (the slot is cloned on each call).
//! - No generic or associated-type methods; no `&mut self`.
//! - Arguments are accepted but not inspected — call verification and
//!   argument matching are deferred to a later iteration.

/// Define a trait and a companion mock struct.
///
/// ```
/// use facts::mockable;
///
/// mockable! {
///     pub trait Clock as ClockMock {
///         fn now(&self) -> u32;
///         fn tzname(&self) -> String;
///     }
/// }
///
/// let clock = ClockMock::new();
/// *clock.now.borrow_mut() = Some(8);
/// ```
///
/// The generated mock exposes each method as a `pub` field of type
/// `RefCell<Option<Return>>`. Calling a method without a value set
/// panics with a descriptive message.
#[macro_export]
macro_rules! mockable {
    (
        $(#[$attr:meta])*
        $vis:vis trait $trait_name:ident as $mock_name:ident {
            $(
                fn $method:ident(&self $(, $arg:ident : $arg_ty:ty )* $(,)?) -> $ret:ty;
            )*
        }
    ) => {
        $(#[$attr])*
        $vis trait $trait_name {
            $(
                fn $method(&self $(, $arg: $arg_ty)*) -> $ret;
            )*
        }

        #[allow(non_snake_case)]
        $vis struct $mock_name {
            $(
                pub $method: ::std::cell::RefCell<::std::option::Option<$ret>>,
            )*
        }

        impl $mock_name {
            pub fn new() -> Self {
                Self {
                    $( $method: ::std::cell::RefCell::new(::std::option::Option::None), )*
                }
            }
        }

        impl ::std::default::Default for $mock_name {
            fn default() -> Self { Self::new() }
        }

        impl $trait_name for $mock_name {
            $(
                fn $method(&self $(, $arg: $arg_ty)*) -> $ret {
                    $( let _ = $arg; )*
                    let borrowed = self.$method.borrow();
                    match borrowed.as_ref() {
                        ::std::option::Option::Some(v) =>
                            <$ret as ::std::clone::Clone>::clone(v),
                        ::std::option::Option::None => panic!(
                            "{}::{}() was called without a provided! expectation",
                            stringify!($mock_name),
                            stringify!($method),
                        ),
                    }
                }
            )*
        }
    };
}

/// Set canned return values on a mock generated by [`mockable!`].
///
/// Single expectation:
///
/// ```ignore
/// provided!(clock.now() => 8);
/// ```
///
/// Multiple expectations share a block:
///
/// ```ignore
/// provided! {
///     clock.now() => 14;
///     clock.tzname() => "UTC".to_string();
/// }
/// ```
///
/// Expands to `*mock.method.borrow_mut() = Some(value);` for each
/// expectation. No call verification yet — a mock whose slot is set
/// but never called will not fail the test.
#[macro_export]
macro_rules! provided {
    ( $( $mock:ident . $method:ident () => $value:expr );+ $(;)? ) => {
        $(
            *$mock.$method.borrow_mut() = ::std::option::Option::Some($value);
        )+
    };
}
